/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Resume from "@/componets/resume";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='shortcut icon'
          href='https://dev.dakidarts.com/wixa/assets/img/favicon.png'
          type='image/x-icon'
        />

        <link
          rel='stylesheet'
          href='https://unicons.iconscout.com/release/v4.0.0/css/line.css'
        />

        <link
          rel='stylesheet'
          href='https://dev.dakidarts.com/wixa/assets/css/swiper-bundle.min.css'
        />

        <link
          rel='stylesheet'
          href='https://dev.dakidarts.com/wixa/assets/css/styles.css'
        />
      </Head>
      <Resume />
    </>
  );
}
